id = "typhoon.zed"
name = "typhoon.zed"
version = "0.0.1"
schema_version = 1
authors = ["Afrizal Fikri <afrizalf96@gmail.com>"]
description = "Typhoon LSP"
repository = "https://github.com/koneko096/typhoon.zed"

[grammars.typhoon]
repository = "https://github.com/koneko096/tree-sitter-typhoon"
rev = "674ea821eb2554a280ba17f263fb57f4a05ec9a1"
